import { SignInButton, SignedIn, SignedOut, UserProfile } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import SignOutButton from "~/components/auth/SignOutButton";

import { api } from "~/utils/api";

const Account: NextPage = () => {
  const posts = api.posts.getAll.useQuery();
  console.log(posts.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 p-4">
        <section>
          <SignedIn>
            <UserProfile />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </section>
      </main>
    </>
  );
};

export default Account;
