import { SignInButton, SignedIn, SignedOut, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import SignOutButton from "~/components/auth/SignOutButton";

import { RouterOutputs, api } from "~/utils/api";

const Home: NextPage = () => {
  const posts = api.posts.getAll.useQuery();
  console.log(posts.data);

  const CreatePost = () => {
    const { user } = useUser();

    return (
      <div>
        <input
          type="text"
          placeholder="Write here..."
          className="p-2 text-black"
        />
      </div>
    );
  };

  type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];

  const PostView = (props: PostWithAuthor) => {
    const { author, post } = props;

    return (
      <div className="border-2 border-solid border-white p-2">
        <img
          src={author.profileImageUrl}
          alt="Profile pic"
          className="float-right w-12"
        />
        <p>{post.authorId}</p>
        <p>{post.content}</p>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 p-4">
        <header>
          <SignedIn>
            <SignOutButton />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </header>
        <section>
          <CreatePost />
        </section>
        <section>
          <div className="flex flex-col gap-4">
            {posts.data?.map((post) => (
              <PostView {...post} key={post.post.id} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
